# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd9a67b5d2841dd4d15827157d9dd08c30ed8fc45a52a7f5ee6e470f58f871b798728577e2d74949adf6ee0733909bb72171097ddd063d52e3ceae3ad5e2eed1

test:
  secret_key_base: 7b7663d55bc26345b5766d4194a2eec98d838bce6a6a8c09ba53013adba930a402bd5c2ff7b15eab05592437ffed9521f2f27b3c26ad87e26bf1a38ea96c501d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
